services:
    client:
        build: ./client
        ports: 
            - 8080:3000
        command: npm run dev
        volumes: 
            - ./client/src:/app/src
    mongodb:
        image: mongo
        volumes: 
            - ./data:/data/db
